### ISSUE TITLE
ORML tokens is not supposed to handle native currency

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#206]
**Describe the bug**
We see that pallet_balances have zero balance even after it is configured in the chain_spec (https://github.com/Polkadex-Substrate/Polkadex/blob/develop/node/src/chain_spec.rs#L309). Also, our current chain_spec is configured to handle native currency in orml_tokens (https://github.com/Polkadex-Substrate/Polkadex/blob/develop/node/src/chain_spec.rs#L400). We need to remove that. 

All balance interactions should be handled via orml_currencies instead of directly interacting with either orml_tokens or pallet_balances

**Comment by zktony** [comment]
Right now, two different pallets are maintaining balances of all Asset on Polkadex Blockchain i.e. Balance Pallet and [ORML's Token Pallet](https://github.com/Polkadex-Substrate/open-runtime-module-library/blob/master/tokens/src/lib.rs#L113-L132). So as discussed with @Gauthamastro Balance Pallet will only handle Native Currency (i.e. PDEX). And Token Pallet will handle other non-native currencies. And [ORML's Currency Pallet](https://github.com/Polkadex-Substrate/open-runtime-module-library/blob/master/currencies/src/lib.rs) will act as abstract layer over these two Pallets. For that we have to update ORML's Currency Pallet so that if Asset Id is PDEX then it uses Pallets Balance's functions otherwise ORML Tokens function.

**Comment by Gauthamastro** [comment]
ORML Currency pallet already has the logic to differentiate the native currency, we just don't know why it's not working

**Comment by zktony** [comment]
> ORML Currency pallet already has the logic to differentiate the native currency, we just don't know why it's not working

I think if we update this then it will work :-
https://github.com/Polkadex-Substrate/Polkadex/blob/main/runtime/src/lib.rs#L1567-L1568

**Comment by frankli-dev** [comment]
https://github.com/open-web3-stack/open-runtime-module-library/issues/499

The issue seems be related to type duplication. By the way, right now there is no way to define the `alias` in polkadotjs app's type definition. So no solution at this moment. 

https://github.com/polkadot-js/apps/issues/5961

**Comment by simonsso** [comment]
Reopen because (1) there was no link to PR and (2) I did not see the PR I merged this morning solves this issue.

Next step update and verify.

**Comment by simonsso** [comment]
https://github.com/Polkadex-Substrate/Polkadex/pull/335
