### ISSUE TITLE
Parachain Rewards Pallet

### ISSUE THREAD

**Issue by nakul1010** [Polkadex-Substrate/Polkadex#594]
### Introduction
Polkadex secured a para chain slot on Polkadot with 973k DOT ($13.8M) contributed to the Polkadex Crowdloan. All the participants who loaned their DOT tokens will receive PDEX tokens. 25% of PDEX tokens receive as rewards can be claimed by participants immediately while the rest of the 75% will linearly unlock. The treasury account will be a pallet account from which rewards funds will be transferred to participants. 

### Flow Diagram
![reward_flow](https://user-images.githubusercontent.com/58786560/213953171-a7835aca-4843-4244-8505-d25ec4defbf8.png)

### Storage Required

**InitializeRewards Map**
Key: reward_id
value: (start_block, end_block, initial_percentage)

**Distributor Map**
Key 1: reward_id
Key 2: account_id
value: (total_reward_amount, claim_amount, is_initial_rewards_claimed, is_initialized, lock_id, last_block_rewards_claim)

### Extrinsic Required

1) `create_reward_cycle`

The extrinsic will be used to start a new reward cycle and can only be called by governance. 
`Parameters`
origin: The sudo/governance address
start_block: The block from where we will start releasing rewards
end_block: By the end_block all rewards should have been released. 
reward_id: The id for which vesting needs to be set. 

----------------------------------------------------

2) `initialize_claim_rewards`
The extrinsic will transfer and lock users' rewards in the user account. It will get user reward_info from the constant hashmap. 
`Parameters`
origin: The users address
reward_id: The id for which vesting needs to be set. 

----------------------------------------------------

3) `claim`
The user will use the extrinsic to claim rewards
`Parameters`
origin: The users address
reward_id: The id for which vesting needs to be set. 

----------------------------------------------------

ToDos
- [x] Design Extrinsics
- [x] Design mocking environment for test cases
- [x] Test Cases

**Comment by mt-gareth** [comment]
Could another extrinsic be created change_reward_destination be added that can be used between add_reward_beneficiaries and initialize_claim_rewards that can be used for a user to change the reward wallet? It would have to be called by the current participant_address and just updates that address?
This would allow users that have different Polkadot and Polkadex wallets to send it to their current Polkadex wallet.
It would also be useful for users that have setup a Polkadex Ledger wallet since the crowdloan to send their rewards to a wallet that is secured by ledger.

**Comment by nakul1010** [comment]
PR [622](https://github.com/Polkadex-Substrate/Polkadex/pull/622) closed it
